events {}

http {

    log_format securigen
        '$remote_addr - $request '
        '$status "$http_user_agent"';

    access_log /var/log/nginx/access.log securigen;

    server {

        listen 8081;

        location / {

            proxy_pass http://securigen-web-honeypot:8080;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}