spring.application.name=securigen-backend

#MySQL Database
spring.datasource.url=jdbc:mysql://localhost:3306/securigen
spring.datasource.username=root
spring.datasource.password=mysql password

#JPA Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true